### ISSUE TITLE
All moves return MoveType.NONE

### ISSUE THREAD

**Issue by haugan** [Stevoisiak/JavaFX-Online-Chess#43]
In the switch statement for result.getType() in CheckersApp, the only case that gets called is NONE. Not quite sure why..

**Comment by Stevoisiak** [comment]
No problem. Wasn't expecting anyone else to actually look through this little student project. :sweat_smile:

**Comment by haugan** [comment]
I'm doing a student project myself, and need to build a Chess game with Java.. Actually, I thought I was commenting on another repo! Haha, time to get some sleep I guess.
