### ISSUE TITLE
Consumer

### ISSUE THREAD

**Issue by AndreJaxanian** [stevoisiak/JavaFX-Online-Chess#48]
https://github.com/stevoisiak/JavaFX-Online-Chess/blob/7ad1336355b0b2ec4bb0144519be629ad89b6b5b/Networking/NetworkConnection.java#L18
would you please explain what is consumer ?
how did u use it and how?

**Comment by stevoisiak** [comment]
To be honest, I don't fully remember what this was used for. (Most of this file is adapted this [guide on networked chat in JavaFX](https://www.youtube.com/watch?v=VVUuo9VO2II))

I believe this was used to "consume" any objects received over the network. In most cases, this object would either be a chat message or a chess move.
