### ISSUE TITLE
??

### ISSUE THREAD

**Issue by AndreJaxanian** [stevoisiak/JavaFX-Online-Chess#49]
https://github.com/stevoisiak/JavaFX-Online-Chess/blob/7ad1336355b0b2ec4bb0144519be629ad89b6b5b/Piece.java#L63

**Comment by AndreJaxanian** [comment]
what does UseSingleMove Exactly do??

**Comment by stevoisiak** [comment]
`usesSingleMove()` is an abstract class that determines whether a piece is limited in how many spaces it can move in one turn.

The King, Knight, and Pawn return `true` for this function, while the Queen and Rook return `false`.

For future reference, the issue tracker's intended use it to report issues with the program, such as bugs or feature requests. Please refrain from opening issues to ask what a piece of code does.
